# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RentBike' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'IQKeyboardManager'
    pod 'SVProgressHUD'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'NVActivityIndicatorView'
    pod 'Toast'
    pod 'SwiftKeychainWrapper'
    
    target 'RentBikeTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'RentBikeUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
